from fpdf import FPDF; import json
import os as access

with open("DETAILS.json", "r") as obj:
    resumeData = json.loads(obj.read())

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()
pdf.set_margin(12.7)

def header_layout(header):
    header.image("JAVIER_Resume Picture.jpg", 152, 10, 50.8)
    header.set_font('helvetica', 'B', 27)
    header.set_text_color(33, 51, 92)
    header.cell(115, 10, "Vienne Kayette L. Javier", ln=True, align='L')
    header.set_font("helvetica", "B", 15)
    header.set_text_color(49, 52, 59)
    header.cell(100, 10, "Quality Assurance Engineer", ln=True, align='L')
    header.ln(8)

def personal_details(personal):
    personal.set_font('helvetica', 'B', 15)
    personal.set_fill_color(224, 224, 224)
    personal.set_text_color(33, 51, 92)
    personal.cell(135, 8, "Personal Information", fill=True, ln=1, align='L')
    personal.ln(1)
    personal.set_font('helvetica', '', 11)
    personal.set_text_color(21, 23, 28)
    personal.cell(40, 6, "Name                   : " + str(resumeData["Personal Information"][0]["Name"]), ln=1)
    personal.cell(40, 6, "Sex                       : " + str(resumeData["Personal Information"][0]["Sex"]), ln=1)
    personal.cell(40, 6, "Age                      : " + str(resumeData["Personal Information"][0]["Age"]), ln=1)
    personal.cell(40, 6, "Address               : " + str(resumeData["Personal Information"][0]["Address"]), ln=1)
    personal.cell(40, 6, "Phone                  : " + str(resumeData["Personal Information"][0]["Contact Number"]), ln=1)
    personal.cell(40, 6, "Email                   : " + str(resumeData["Personal Information"][0]["Email Address"]), ln=1)
    personal.ln(4)

def prosum_details(summary):
    summary.set_font('helvetica', 'B', 15)
    summary.set_fill_color(224, 224, 224)
    summary.set_text_color(33, 51, 92)
    summary.cell(0, 8, "Professional Summary", fill=True, ln=1, align='L')
    summary.ln(1)
    summary.set_font("helvetica", "", 11)
    summary.set_text_color(20, 23, 28)
    summary.cell(40, 6, '' + str(resumeData["Professional Summary"][0]), ln=1)
    summary.cell(40, 6, '' + str(resumeData["Professional Summary"][1]), ln=1)
    summary.cell(40, 6, '' + str(resumeData["Professional Summary"][2]), ln=1)
    summary.cell(40, 6, '' + str(resumeData["Professional Summary"][3]), ln=1)
    summary.ln(4)

def skills_details(skill):
    skill.set_font("helvetica", 'B', 15)
    skill.set_fill_color(224, 224, 224)
    skill.set_text_color(33, 51, 92)
    skill.cell(0, 8, "Core Skills", fill=True, ln=1, align='L')
    skill.ln(1)
    skill.set_font('helvetica', '', 11)
    skill.set_text_color(20, 23, 28)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][0]), ln=0)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][1]), ln=0)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][2]), ln=1)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][3]), ln=0)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][4]), ln=0)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][5]), ln=1)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][6]), ln=0)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][7]), ln=0)
    skill.cell(68, 6, '' + str(resumeData["Core Skills"][8]), ln=1)
    skill.ln(4)

def employment_details(emp):
    emp.set_font("helvetica", "B", 15)
    emp.set_fill_color(224, 224, 224)
    emp.set_text_color(33, 51, 92)
    emp.cell(0, 8, "Employment History", fill=True, ln=1, align='L')
    emp.ln(1)
    emp.set_font('helvetica', 'B', 11)
    emp.set_text_color(20, 23, 28)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Former Work"]), ln=1)
    emp.set_text_color(96, 96, 96)
    emp.set_font('helvetica', 'BI', 11)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Former Company"]), ln=1)
    emp.set_text_color(0, 0, 0)
    emp.set_font('helvetica', '', 11)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Former Description"][0]), ln=1)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Former Description"][1]), ln=1)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Former Description"][2]), ln=1)
    emp.ln(3)
    emp.set_font('helvetica', 'B', 11)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Latter Work"]), ln=1)
    emp.set_text_color(96, 96, 96)
    emp.set_font('helvetica', 'BI', 11)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Latter Company"]), ln=1)
    emp.set_text_color(0, 0, 0)
    emp.set_font('helvetica', '', 11)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Latter Description"][0]), ln=1)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Latter Description"][1]), ln=1)
    emp.cell(40, 6, '' + str(resumeData["Employment History"][0]["Latter Description"][2]), ln=1)
    emp.ln(4)

def education_details(educ):
    educ.set_font('helvetica', 'B', 15)
    educ.set_fill_color(224, 224, 224)
    educ.set_text_color(33, 51, 92)
    educ.cell(0, 8, "Education", fill=True, ln=1, align='L')
    educ.ln(1)
    educ.set_text_color(0, 0, 0)
    educ.set_font('helvetica', 'B', 11)
    educ.cell(40, 6, '' + str(resumeData["Education"][0]["Course"]), ln=1)
    educ.set_text_color(96, 96, 96)
    educ.set_font('helvetica', 'BI', 11)
    educ.cell(40, 6, '' + str(resumeData["Education"][0]["University"]), ln=1)
    educ.set_text_color(0, 0, 0)
    educ.set_font('helvetica', '', 11)
    educ.cell(40, 6, '' + str(resumeData["Education"][0]["Address"]), ln=1)
    educ.ln(4)

def certs_details(cert):
    cert.set_font('helvetica', 'B', 15)
    cert.set_fill_color(224, 224, 224)
    cert.set_text_color(33, 51, 92)
    cert.cell(0, 8, "Awards, Certifications, & Additional Training", fill=True, ln=1, align='L')
    cert.ln(1)
    cert.set_text_color(0, 0, 0)
    cert.set_font('helvetica', 'BI', 11)
    cert.cell(40, 6, '' + str(resumeData["Certifications"][0]["Certification 1"]), ln=1)
    cert.set_font('helvetica', '', 11)
    cert.cell(40, 6, '' + str(resumeData["Certifications"][0]["Description 1"]), ln=1)
    cert.set_font('helvetica', 'BI', 11)
    cert.ln(2)
    cert.cell(40, 6, '' + str(resumeData["Certifications"][0]["Certification 2"]), ln=1)
    cert.set_text_color(0, 0, 0)
    cert.set_font('helvetica', '', 11)
    cert.cell(40, 6, '' + str(resumeData["Certifications"][0]["Description 2"]), ln=1)
    cert.set_font('helvetica', 'BI', 11)
    cert.ln(2)
    cert.cell(40, 6, '' + str(resumeData["Certifications"][0]["Certification 3"]), ln=1)
    cert.ln(4)

def ref_details(ref):
    ref.set_font("helvetica", "B", 15)
    ref.set_fill_color(224, 224, 224)
    ref.set_text_color(33, 51, 92)
    ref.cell(0, 8, "Professional & Character References", fill=True, ln=1, align='L')
    ref.ln(1)
    ref.set_font('helvetica', '', 11)
    ref.set_text_color(0, 0, 0)
    ref.cell(40, 6, '' + str(resumeData["Professional & Character References"][0]), ln=1)
    ref.ln(4)

def resume_PDF():
    header_layout(pdf)
    personal_details(pdf)
    prosum_details(pdf)
    skills_details(pdf)
    employment_details(pdf)
    education_details(pdf)
    certs_details(pdf)
    ref_details(pdf)

resume_PDF()

pdf.set_auto_page_break(margin = 0.5, auto = True) 
pdf.output("JAVIER_VIENNEKAYETTE.pdf")
access.startfile("JAVIER_VIENNEKAYETTE.pdf")